[target.riscv32imac-unknown-none-elf]
runner = [
  "probe-rs",
  "run",
  "--chip",
  "esp32c6",
  "--connect-under-reset",
  "--log-format",
  "{L} {s}",
]

[build]
target = "riscv32imac-unknown-none-elf"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
  "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "info"

[unstable]
build-std = ["alloc", "core"]
#build-std-features = ["panic_immediate_abort"]